spring:
  cloud:
    alicloud:
      access-key:test
      secret-key:test
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
    nacos:
      discovery:
        server-addr: 192.168.65.10:8848
  application:
    name: neighbour-third-party

server:
  port: 13000