spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 169.254.68.20:8848
    gateway:
      routes:
        - id: test-route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq-route
          uri: http://www.qq.com
          predicates:
            - Query=url,qq

server:
  port: 88
